spring:
  profiles: 
    active:
      - dev
---
spring: 
  profiles: dev  # 开发环境
    application: 
      name: microservicecloud-config-demo-dev
---
spring: 
  profiles: test
  application: microservicecloud-config-demo-test
# 请保存为UTF-8格式